Update automerge.yaml

diff --git a/.github/workflows/automerge.yaml b/.github/workflows/automerge.yaml
--- a/.github/workflows/automerge.yaml
+++ b/.github/workflows/automerge.yaml
@@ -45,7 +45,7 @@ jobs:
 
       - name: 'Wait for status checks to Pass'
         id: waitforstatuschecks
-        uses: "WyriHaximus/github-action-wait-for-status@v2"
+        uses: "WyriHaximus/github-action-wait-for-status@v1.7.1"
         with:
           ignoreActions: "Automerge auto-cherry-picked pr"
           checkInterval: 60
@@ -69,5 +69,6 @@ jobs:
           if [ "${{ steps.automerge.outputs.mergeResult }}" == 'merged' ]; then
             echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} is Auto Merged !"
           else
-            echo "::error Auto Merge of Pull request ${{ steps.automerge.outputs.pullRequestNumber }} is ${{steps.automerge.outputs.mergeResult}} !"
+            echo "::error Auto Merge for Pull request failed !"
+            exit 1
           fi
