Update automerge.yaml

diff --git a/.github/workflows/automerge.yaml b/.github/workflows/automerge.yaml
--- a/.github/workflows/automerge.yaml
+++ b/.github/workflows/automerge.yaml
@@ -44,30 +44,31 @@ jobs:
           echo "Waiting for ~ 10 mins, PRT to be initiated." && sleep 60
           
       - name: is PRT check Passed ?
-        run: |
+        run: | 
           counter=0
-          STATUSES=$(curl -s https://api.github.com/repos/${{github.repository}}/statuses/${{ github.head_ref }}  | jq -r 'length')
+          STATUSES=$(curl -s https://api.github.com/repos/omkarkhatavkar/robottelo/statuses/cherry-pick-6.12.z-fe828943c2c93c775997c2622de95c757dbd8640  | jq -r 'length')
           if [ $STATUSES == 0 ]; then
               echo "::error PRT failed to start ! Stopping."
               exit 1
           else
-              CONTEXT=$(curl -s https://api.github.com/repos/${{github.repository}}/statuses/${{ github.head_ref }}  | jq -r '.[0].context')
+              CONTEXT=$(curl -s https://api.github.com/repos/omkarkhatavkar/robottelo/statuses/cherry-pick-6.12.z-fe828943c2c93c775997c2622de95c757dbd8640  | jq -r '.[0].context')
               COMMIT_STATUS="pending"
-              if ["$CONTEXT" == "Robottelo-Runner"]; then
-                  until [ "$COMMIT_STATUS" == "success" ] || [ "$COMMIT_STATUS" == "failure" ] || [$counter -gt 10]; do
+              if [ "$CONTEXT" == "Robottelo-Runner" ]; then
+                  until [ "$COMMIT_STATUS" == "success" ] || [ "$COMMIT_STATUS" == "failure" ] || [ $counter -gt 10 ]; do
                       sleep 300
-                      COMMIT_STATUS=$(curl -s https://api.github.com/repos/${{github.repository}}/statuses/${{ github.head_ref }}  | jq -r '.[0].state')
+                      COMMIT_STATUS=$(curl -s https://api.github.com/repos/omkarkhatavkar/robottelo/statuses/cherry-pick-6.12.z-fe828943c2c93c775997c2622de95c757dbd8640  | jq -r '.[0].state')
                       echo "Waiting for PRT to complete....."
                       echo "Robottelo-Runner - $COMMIT_STATUS"
                   done
+              else
+                  echo "::error Failed to get Robottelo-Runner status " && exit 1 
               fi
-              if ["$COMMIT_STATUS" == "success"] then;
+              if [ "$COMMIT_STATUS" == "success" ]; then
                   echo "PRT Passed Successfully!"
               else
                   echo "::error PRT failed ! or PRT timeout !"
               fi
           fi
-
       - name: 'Wait for status checks to Pass'
         id: waitforstatuschecks
         uses: lewagon/wait-on-check-action@v1.2.0
